from .profile import Profile
from .province import Province
from .city import City
from .industry import Industry
from .profession import Profession
from .company import Company
from .job import Job
from .applied_jobs import AppliedJob
from .skill import Skill
from .watchlist import Watchlist
from .personal_quality import PersonalQuality
from .language import Language