# Generated by Django 5.1.1 on 2024-10-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_logo_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='minimum_experience',
            field=models.CharField(blank=True, choices=[('Nybörjare', 'Nybörjare'), ('Junior', 'Junior'), ('Erfaren', 'Erfaren'), ('Senior', 'Senior'), ('Expert', 'Expert')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_type',
            field=models.CharField(blank=True, choices=[('På plats', 'På plats'), ('Distans', 'Distans')], max_length=32, null=True),
        ),
    ]
